### ISSUE TITLE
CC3200 EMT — Differentiate CC3200 EMT from CC3200 Boards Tags

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#10]
Both **CC3200 EMT** and **CC3200** share the same board tag `CC3200-LAUNCHXL`.

Similarly, use `_` instead of `-` to avoid any compilation issue as mentioned at 

* https://github.com/energia/msp430-lg-core/issues/4,
* https://github.com/energia/msp430-lg-core/issues/9, and 
* https://github.com/energia/tivac-core/issues/4.

**Comment by rei-vilo** [comment]
On Energia release 17, **CC3200** was `lpcc3200`while **CC3200 EMT** was `lpcc3200EMT`.

Same for the other CC3200-based RedBearLab boards.

**Comment by rei-vilo** [comment]
Another issue, the `build.mcu` entry is repeated twice.

```
CC3200_LAUNCHXL_EMT.build.mcu=cortex-m4
```

**Comment by robertinant** [comment]
This issue was moved to energia/cc3200emt-core#3
