### ISSUE TITLE
CC3200 EMT — Create a specific CC3200 EMT repository for issue tracking 

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#11]
Please create a specific CC3200 EMT repository for issue tracking.

**Comment by rei-vilo** [comment]
Affected issues #6 #8 #9 #10.

**Comment by robertinant** [comment]
done: https://github.com/energia/cc3200emt-core

**Comment by robertinant** [comment]
This issue was moved to energia/cc3200emt-core#4
