### ISSUE TITLE
Slave I²C Not Implemented

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#2]
Slave I²C is not implemented for CC3200.
- Error

> /var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/buildcbd00b46c3f98c5befd14c5298baa174.tmp/sketch/sketch_jun29a.ino.cpp.o: In function `setup':
> /var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/arduino_modified_sketch_540132/sketch_jun29a.ino:5: undefined reference to`TwoWire::begin(int)'
> collect2: error: ld returned 1 exit status
> Using library Wire at version 1.0.1 in folder: /Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/libraries/Wire 
> exit status 1
> Error compiling for board CC3200-LAUNCHXL (80MHz).
- Code

```
#include "Wire.h"

void setup() {
  // put your setup code here, to run once:
  Wire.begin(0x18);
}

void loop() {
  // put your main code here, to run repeatedly: 

}
```

**Comment by rei-vilo** [comment]
See https://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/t/373617

**Comment by robertinant** [comment]
I currently do not plan to implement I2C slave for the CC3200.
