### ISSUE TITLE
warning: ISO C99 requires whitespace after the macro name

### ISSUE THREAD

**Issue by Zv1k0** [energia/cc3200-core#25]
Hello, I'm new to this and I'm probably doing something wrong and that's why I'm here. I get this message in the title when i try to Verify the code and i cant fix it. I've seen other threads with different boards and how they fixed the problem. So i tried the same with CC3200 launchpad by changing the boards.txt file.

I changed the line:
CC3200-LAUNCHXL.build.board=CC3200-LAUNCHXL
to this:
CC3200-LAUNCHXL.build.board=CC3200_LAUNCHXL

I also added this:
{"name": "CC3200_LAUNCHXL"},
to package_index(JSON File)

None of this didn't fix the problem, I still get the same message. Anything else i can do?

**Comment by StefanSch** [comment]
this should help:
change in boards.txt (note: change is behind the =)
CC3200-LAUNCHXL.build.variant=CC3200_LAUNCHXL
CC3200-LAUNCHXL.build.board=CC3200_LAUNCHXL


change folder name otherwise the compiler does not find some include files:
energia\hardware\cc3200\1.0.3\variants\CC3200-LAUNCHXL\
to
energia\hardware\cc3200\1.0.3\variants\CC3200_LAUNCHXL\

**Comment by Zv1k0** [comment]
Thank you very much for you answer @StefanSch and I'm sorry for so late reply, i had a terrible disease. I've tried your solution and now i don't get the warning anymore so thank you very much. Now i get this (picture) when i compile example under basic and blink. Is this even a problem because if I compile it again it doesn't show anymore. Also, do i have to change anything in the code in basics examples (blink) for red led to blink? I've read somewhere that it should work on most CC3200 Launchpads. 

![energia](https://user-images.githubusercontent.com/36442284/36423906-e00fc874-1641-11e8-86a1-7c4c29ab44d8.PNG)

**Comment by StefanSch** [comment]
Define warning fixed with pull request #26
