### ISSUE TITLE
CC3200 SPI Issue

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#5]
When the SPI library is called from a library, compilation fails, even when SPI has been included in the main sketch.

> "/Users/ReiVilo/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++" -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD -mcpu=cortex-m4 -mthumb -DF_CPU=80000000L -DARDUINO=10610 -DENERGIA=10610 -DENERGIA_CC3200-LAUNCHXL -DENERGIA_ARCH_CC3200 "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/variants/CC3200-LAUNCHXL" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/system/driverlib" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/system/inc" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/system" -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/cores/cc3200" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/variants/CC3200-LAUNCHXL" "/var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/build2bd1d110e6c47d509a7edf46f7b5491e.tmp/sketch/myLibrary.cpp" -o "/var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/build2bd1d110e6c47d509a7edf46f7b5491e.tmp/sketch/myLibrary.cpp.o"
> In file included from /var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/build2bd1d110e6c47d509a7edf46f7b5491e.tmp/sketch/myLibrary.h:1:0,
>                  from /var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/build2bd1d110e6c47d509a7edf46f7b5491e.tmp/sketch/myLibrary.cpp:1:
> /Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/system/driverlib/SPI.h:143:57: error: 'tBoolean' has not been declared
>  extern unsigned long SPIIntStatus(unsigned long ulBase, tBoolean bMasked);
>                                                         ^
> /var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/build2bd1d110e6c47d509a7edf46f7b5491e.tmp/sketch/myLibrary.cpp: In function 'void beginSPI()':
> myLibrary.cpp:5: error: 'SPI' was not declared in this scope
>   SPI.begin();
>   ^
> exit status 1
> 'SPI' was not declared in this scope
- Solution

The `arm-none-eabi-g++` command line is missing the include `-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/libraries/SPI`.
- **CC3200_SPI_issue.ino**

```
#include "myLibrary.h"
#include "SPI.h"

void setup() {
  // put your setup code here, to run once:
  beginSPI();
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
- **myLibrary.h**

```
#include "SPI.h"


void beginSPI();
```
- **myLibrary.cpp**

```
#include "myLibrary.h"

void beginSPI()
{
  SPI.begin();

}

```

**Comment by rei-vilo** [comment]
Actually, there are two SPI libraries:

* **spi.h** at `/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/system/driverlib/spi.h`

* **SPI.h** at `/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/libraries/SPI/SPI.h`

**Comment by rei-vilo** [comment]
**Orfer matters!**

* If `hardware/cc3200/1.0.2/system/driverlib` is included before `hardware/cc3200/1.0.2/libraries/SPI/`, compilation fails, because `hardware/cc3200/1.0.2/libraries/SPI/` isn't taken into account.

* If `hardware/cc3200/1.0.2/libraries/SPI/` is included before `hardware/cc3200/1.0.2/system/driverlib`, compilation succeeds.

**Comment by tom-giesberg** [comment]
How can I make use of the "solution" above? Is there a make file or something to edit?

Thanks in advance.

**Comment by robertinant** [comment]
You can easily work around it for now by editing the file: <Energia packages location>/Energia15/packages/energia/hardware/cc3200/1.0.2/platform.txt. Look for:

```
compiler.driverlib.c.flags="-I{build.system.path}/driverlib" "-I{build.system.path}/inc" "-I{build.system.path}”
and replace it with:
compiler.driverlib.c.flags="-I{build.system.path}" "-I{build.system.path}/inc" "-I{build.system.path}”
```

**Comment by rei-vilo** [comment]
Is this trick also valid for the Pervasive Displays library?

Thank you.

**Comment by robertinant** [comment]
Yes it is. The issue is that there is a C compiler include flag that points at {build.system.path}/driverlib. This is an error and it should be {build.system.path}. Driverlib headers should be included with driverlib/xzy.h

**Comment by tom-giesberg** [comment]
Thanks, Robert, it worked like a charm.

**Comment by rei-vilo** [comment]
For Mac OS X users: 

- Full path is `~/Library/Energia15/packages/energia/hardware/cc3200/1.0.2/platform.txt`

**Comment by sri30** [comment]
I'm facing the same problem as well,but I'm running Energia on Windows 10. Could you please help me out?

**Comment by rei-vilo** [comment]
You need to look for the corresponding folder on Windows and perform the same operation as in https://github.com/energia/cc3200-core/issues/5#issuecomment-247780464

**Comment by sri30** [comment]
I'm using Energia version 1.6.10E18, and in the path 
E:\energia-1.6.10E18-windows\energia-1.6.10E18\hardware\energia
the only folder I can find is named MSP30 even though I've installed the CC3200 board support package from the board manager.
There is only one platform.txt file in the entire Energia installation folder and it doesn't have the above lines of code in it.
Appreciate the help,thanks.

**Comment by StefanSch** [comment]
On windows the path looks like this:
c:\Users\yourname\AppData\Local\Energia15\packages\energia\hardware\cc3200\1.0.2\platform.txt

**Comment by sri30** [comment]
Thank you so much@StefanSch . The sketch compiles without errors now. :-)

**Comment by rei-vilo** [comment]
Although this issue is closed, the [solution](https://github.com/energia/cc3200-core/issues/5#issuecomment-247780464) should be committed.

**Comment by robertinant** [comment]
Fixed and committed.

**Comment by rei-vilo** [comment]
Thanks!

**Comment by rei-vilo** [comment]
Still to be released.
