### ISSUE TITLE
Energia 18 — CC3200 Energia MT Implementation?

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#6]
Any plans for implementing Energia MT on CC3200?

**Comment by rosenk** [comment]
[http://energia.nu/pin-maps/guide_cc3200launchpad/](http://energia.nu/pin-maps/guide_cc3200launchpad/)

> Energia MT is supported for CC3200. You can make use of multi-tasking in your Energia sketches and automatically enter low power modes when idle.

**Comment by rei-vilo** [comment]
Energia 17 does support CC3200 with MT, but MT for CC3200 isn't implemented yet for the CC3200.

> The CC3200 (MT) TI-RTOS based multitasking based core will be made available in the near future through the board manager. 

_at http://energia.nu_

**Comment by rosenk** [comment]
I'm sorry, but I don't understand how something is simultaniously supported but not implemented. It is a contradiction.

**Comment by robertinant** [comment]
You can get a beta through adding the following link in the preferences->Additional Boards Manager URL's.

http://energia.nu/packages/package_energia_beta_index.json

I will be officially releasing it early January.

**Comment by rei-vilo** [comment]
The link points to the wrong package, actually the CC3200 standard boards.

```
          "name": "Energia CC3200 EMT boards",
          "architecture": "cc3200emt",
          "version": "1.0.0",
          "category": "Energia",
          "url": "http://energia.nu/downloads/download_core.php?file=cc3200-1.0.2.tar.bz2",
          "archiveFileName": "cc3200-1.0.2.tar.bz2",
```
