### ISSUE TITLE
CC3200 EMT — CC3200 and CC3200 EMT Tools > Board Menu

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#8]
Testing #6

`CC3200` and `CC3200 EMT` appear the same.

<img width="330" alt="capture 2016-12-21 a 08 31 41" src="https://cloud.githubusercontent.com/assets/951776/21380868/5fab5e48-c758-11e6-8a35-7a2acb2c71eb.png">

**Comment by robertinant** [comment]
This issue was moved to energia/cc3200emt-core#1
