### ISSUE TITLE
CC3200 EMT — MultiBlink Fails to Compile Against CC3200 EMT 

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc3200-core#9]
The `MultiBlink example fails to compile against CC3200 EMT, but succeeds agains MSP432 EMT.

1. `BLUE_LED` is unknown, should be replaced by `YELLOW_LED`

Add 

```
#define BLUE_LED YELLOW_LED
```

2. Linking fails, with the following error message

> Linking everything together...
> "/Users/ReiVilo/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++" -mcpu=cortex-m4 -mthumb -nostartfiles -nostdlib -Os -Wl,--gc-sections "-T/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200emt/1.0.0/cores/cc3200/cc3200.ld" "-Wl,-Map,/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp/MultiBlink.ino.map"  -o "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp/MultiBlink.ino.elf" "-L/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp" -Wl,--check-sections -Wl,--cref -Wl,--gc-sections -Wl,--entry=ResetISR -Wl,--unresolved-symbols=report-all -Wl,--warn-common -mthumb -mcpu=cortex-m4 -mfloat-abi=soft -mabi=aapcs -Wl,--start-group "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp/sketch/MultiBlink.ino.cpp.o" "/var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp/core/core.a" -Wl,--end-group "/Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200emt/1.0.0/system/driverlib/libdriverlib.a" -lm -lc -lgcc
> /var/folders/px/cyfvtr757lqg0yp_cv9j79jh0000gn/T/build63d44f843ff038a6bc73c3b80b8f85e0.tmp/core/core.a(main.cpp.o): In function `main':
> /Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200emt/1.0.0/cores/cc3200/main.cpp:39: undefined reference to `setup'
> /Users/ReiVilo/Library/Energia15/packages/energia/hardware/cc3200emt/1.0.0/cores/cc3200/main.cpp:42: undefined reference to `loop'
> collect2: error: ld returned 1 exit status
> exit status 1
> Error compiling for board CC3200-LAUNCHXL EMT (80MHz).

**Comment by rei-vilo** [comment]
Adding empty `setup()` and `loop()` to the `MultiBlink.ino` file solved the case.

```
void setup() { }

void loop() { }
```

It looks like the task parser doesn't behave the same way against the CC3200 and the MSP432.

**Comment by robertinant** [comment]
This issue was moved to energia/cc3200emt-core#2
